insert into categories(category_id, category_name) values (1,'U.S. States');
insert into questions(category_id, question, question_type, answer, difficulty) values (1,'This state''s capital is known as the sailing capital of the world.','What is','maryland',1);
insert into questions(category_id, question, question_type, answer, difficulty) values (1,'This state is known as the golden state.','What is','california',2);
insert into questions(category_id, question, question_type, answer, difficulty) values (1,'This state is home to the oldest continuously held horse race in the country.','What is','kentucky',3);
insert into questions(category_id, question, question_type, answer, difficulty) values (1,'At 11,239 feet, Mount Hood stands as the tallest peak of this state.','What is','oregon',4);
insert into questions(category_id, question, question_type, answer, difficulty) values (1,'This state''s name is the only one to start with two vowels','What is','iowa',5);
insert into categories(category_id, category_name) values (2,'Math & Science');
insert into questions(category_id, question, question_type, answer, difficulty) values (2,'This type of triangle has three equal length sides.','What is','equilateral',1);
insert into questions(category_id, question, question_type, answer, difficulty) values (2,'This degree in Fahrenheit is the temperature in which water freezes.','What is','32',2);
insert into questions(category_id, question, question_type, answer, difficulty) values (2,'This math type of math expression will always contain an equals sign.','What is an','equation',3);
insert into questions(category_id, question, question_type, answer, difficulty) values (2,'This is the third planet closest to the sun in our galaxy.','What is','Earth',4);
insert into questions(category_id, question, question_type, answer, difficulty) values (2,'This type of mathematical operation will result in a quotient','What is','division',5);
insert into categories(category_id, category_name) values (3,'U.S. Geography');
insert into questions(category_id, question, question_type, answer, difficulty) values (3,'This city is known as the city of "Brotherly Love".','What is','Philidelphia',1);
insert into questions(category_id, question, question_type, answer, difficulty) values (3,'This valley is known to be lowest point in the United States.','What is','Death Valley',2);
insert into questions(category_id, question, question_type, answer, difficulty) values (3,'This lake is the largest Great Lake, and the largest lake in North America.','What is','Lake Superior',3);
insert into questions(category_id, question, question_type, answer, difficulty) values (3,'This state is known for the fuzzy fruit they farm.','What is','Georgia',4);
insert into questions(category_id, question, question_type, answer, difficulty) values (3,'Mount Rushmore is located in which state','What is','South Dakota',5);
insert into categories(category_id, category_name) values (4,'World History');
insert into questions(category_id, question, question_type, answer, difficulty) values (4,'This famous British ship sunk in 1912 after it hit an iceburg.','What is the','Titanic',1);
insert into questions(category_id, question, question_type, answer, difficulty) values (4,'This ancient leader founded the city Alexandria, Eygypt.','Who is','Alexander the Great',2);
insert into questions(category_id, question, question_type, answer, difficulty) values (4,'This year was the year Archduke Franz Ferdinand was assasinated and the beginning of World War I','What is','1914',3);
insert into questions(category_id, question, question_type, answer, difficulty) values (4,'This country was formerly known as the U.S.S.R.','What is','Russia',4);
insert into questions(category_id, question, question_type, answer, difficulty) values (4,'The One-Hundred Years War was fought between England and this country.','What is','France',5);
insert into categories(category_id, category_name) values (5,'Disney Characters');
insert into questions(category_id, question, question_type, answer, difficulty) values (5,'This character was Buzz Light Year''s best friend in the Toy Story movies.','Who is','Woody',1);
insert into questions(category_id, question, question_type, answer, difficulty) values (5,'Based off a real historic character, this disney princess helped save John Smith','Who is','Pocohontas',2);
insert into questions(category_id, question, question_type, answer, difficulty) values (5,'This mouse is often regarded as the beginning of the Disney franchise','Who is','Mickey Mouse',3);
insert into questions(category_id, question, question_type, answer, difficulty) values (5,'Snow White bit into this poisoned fruit before she fell asleep.','What is an','apple',4);
insert into questions(category_id, question, question_type, answer, difficulty) values (5,'This yellow and blue fish was Ariel''s best friend in The Little Mermaid','Who is','Flounder',5);
insert into categories(category_id, category_name) values (6,'Months of the Year');
insert into questions(category_id, question, question_type, answer, difficulty) values (6,'Martin Luther King jr Day is celebrated in this month.','What is','February',1);
insert into questions(category_id, question, question_type, answer, difficulty) values (6,'This month is when Summer offically ends','What is','September',2);
insert into questions(category_id, question, question_type, answer, difficulty) values (6,'The Jewish celebrated holiday, Passover occurs in this month','What is','April',3);
insert into questions(category_id, question, question_type, answer, difficulty) values (6,'The U.S.A''s Independence Day is celebrated in this month','What is','July',4);
insert into questions(category_id, question, question_type, answer, difficulty) values (6,'The Presidential Inaguration occurs every four years in this month','What is','January',5);
insert into categories(category_id, category_name) values (7,'Animals');
insert into questions(category_id, question, question_type, answer, difficulty) values (7,'Panda''s diets almost exclusively consist of this plant','What is','bamboo',1);
insert into questions(category_id, question, question_type, answer, difficulty) values (7,'This animal is known for being the fastest mammal on earth.','What is a','cheetah',2);
insert into questions(category_id, question, question_type, answer, difficulty) values (7,'A group of lions is known as this','What is','pride',3);
insert into questions(category_id, question, question_type, answer, difficulty) values (7,'This type of animal eats both plants and meat.','What is','Omnivore',4);
insert into questions(category_id, question, question_type, answer, difficulty) values (7,'Animals with pouches to carry their young are known as this.','What are','marsupials',5);
insert into categories(category_id, category_name) values (8,'Art & Literature');
insert into questions(category_id, question, question_type, answer, difficulty) values (8,'This author wrote the famous novel Adventures of Huckleberry Finn.','Who is','Mark Twain',1);
insert into questions(category_id, question, question_type, answer, difficulty) values (8,'This painter, who shares his name with a Teenage Mutant Ninja Turtle, painted the Mona Lisa','Who is','Leonardo da Vinci',2);
insert into questions(category_id, question, question_type, answer, difficulty) values (8,'This was the name of Harry Potter''s pet owl','Who is','Hedwig',3);
insert into questions(category_id, question, question_type, answer, difficulty) values (8,'The famous melting clock painting was made by this painter who also had cut off his own ear','Who is','Salvador Dali',4);
insert into questions(category_id, question, question_type, answer, difficulty) values (8,'Peter Pan''s pirate enemy went by this name.','Who is','Captain Hook',5);
insert into categories(category_id, category_name) values (9,'Nature');
insert into questions(category_id, question, question_type, answer, difficulty) values (9,'Dandelions are this bright color','What is','yellow',1);
insert into questions(category_id, question, question_type, answer, difficulty) values (9,'This largest planet in our solar system also had a large red spot on it.','What is','Jupiter',2);
insert into questions(category_id, question, question_type, answer, difficulty) values (9,'The term "feline" is usually referring to this type of animal','What is a','cat',3);
insert into questions(category_id, question, question_type, answer, difficulty) values (9,'This process is used by many organisms to convert light to energy','What is','photosynthesis',4);
insert into questions(category_id, question, question_type, answer, difficulty) values (9,'This is the inner most color of the rainbow','What is','violet',5);
insert into categories(category_id, category_name) values (10,'Sports');
insert into questions(category_id, question, question_type, answer, difficulty) values (10,'Crawl, backstroke and butterfly are all techniques in this sport.','What is','swimming',1);
insert into questions(category_id, question, question_type, answer, difficulty) values (10,'In ten-pin bowling when you knock down all ten pins after your second bowl is called this','What is a','spare',2);
insert into questions(category_id, question, question_type, answer, difficulty) values (10,'This chess-piece you can only move diagonally','What is a','bishop',3);
insert into questions(category_id, question, question_type, answer, difficulty) values (10,'Martial arts experts wear this color belt','What is','black',4);
insert into questions(category_id, question, question_type, answer, difficulty) values (10,'This is the number of players it takes to field a baseball team','What is','9',5);
insert into categories(category_id, category_name) values (11,'World Travel');
insert into questions(category_id, question, question_type, answer, difficulty) values (11,'This is the largest country in the world','What is','Russia',1);
insert into questions(category_id, question, question_type, answer, difficulty) values (11,'This Italian city Is famous for its canals','What is','Venice',2);
insert into questions(category_id, question, question_type, answer, difficulty) values (11,'Africa has this longest river running through it','What is the','Nile River',3);
insert into questions(category_id, question, question_type, answer, difficulty) values (11,'Canada and this country share its borders with the USA','What is','Mexico',4);
insert into questions(category_id, question, question_type, answer, difficulty) values (11,'This mountain is considered the most difficult to climb in the world.','What is','Mount Everest',5);
insert into categories(category_id, category_name) values (12,'Bugs and Insects');
insert into questions(category_id, question, question_type, answer, difficulty) values (12,'This red and black spotted bug is considered good luck in some cultures','What is a','Lady Bug',1);
insert into questions(category_id, question, question_type, answer, difficulty) values (12,'A caterpillar is a butterfly in this stage of its life cycle','What is','Larva',2);
insert into questions(category_id, question, question_type, answer, difficulty) values (12,'All insects have this many legs total','What is','6',3);
insert into questions(category_id, question, question_type, answer, difficulty) values (12,'The mid-section of an insect is called this','What is a','thorax',4);
insert into questions(category_id, question, question_type, answer, difficulty) values (12,'Insects will use these to help them find and feel for food','What is','antennae',5);
insert into categories(category_id, category_name) values (13,'Pop Culture');
insert into questions(category_id, question, question_type, answer, difficulty) values (13,'This singer and actress was first famous for her role in Hannah Montana','Who is','Miley Cyrus',1);
insert into questions(category_id, question, question_type, answer, difficulty) values (13,'Known for his action filled movies like Top-Gun and Mission Impossible is this actor','Who is','Tom Cruise',2);
insert into questions(category_id, question, question_type, answer, difficulty) values (13,'What new Taylor Swift album contains the songs "Shake it Off" and "Blank Space"','What is','1989',3);
insert into questions(category_id, question, question_type, answer, difficulty) values (13,'These colorful characters have a theme song proclaiming "Gotta Catch Em All"','What is','pokemon',4);
insert into questions(category_id, question, question_type, answer, difficulty) values (13,'This famous boy-band is popular for songs like "What Makes You Beautiful" and "Kiss You"','Who is','One Direction',5);
insert into categories(category_id, category_name) values (14,'Turn on Your Computer');
insert into questions(category_id, question, question_type, answer, difficulty) values (14,'Of Flash, Google or AltaVista, the one that''s not a popular Internet search engine','What is','Flash',1);
insert into questions(category_id, question, question_type, answer, difficulty) values (14,'This 2-letter Windows computer operating system was introduced in October 2001','What is','XP',2);
insert into questions(category_id, question, question_type, answer, difficulty) values (14,'Abbreviated BB, it''s a popular data-transmission method capable of sending multiple channels at once','What is','broadband',3);
insert into questions(category_id, question, question_type, answer, difficulty) values (14,'In computerese, it''s what the P stands for in the abbreviation HTTP','What is','protocol',4);
insert into questions(category_id, question, question_type, answer, difficulty) values (14,'The forerunner to the Internet known as the ARPANET was a 1960s network by this U.S. government dept.','What is','defense',5);
insert into categories(category_id, category_name) values (15,'Languages');
insert into questions(category_id, question, question_type, answer, difficulty) values (15,'This language is the second most-spoken in the U.S. with about 35 million speakers','What is','spanish',1);
insert into questions(category_id, question, question_type, answer, difficulty) values (15,'The region of Flanders is known as Vlaanderen in Flemish, which is a form of this language.','What is','Dutch',2);
insert into questions(category_id, question, question_type, answer, difficulty) values (15,'On the dance floor I''m a klutz, from a word meaning "wooden block" in this Germanic language.','What is','yiddish',3);
insert into questions(category_id, question, question_type, answer, difficulty) values (15,'Dialects of English include this London one with distinctive rhymic slang.','What is','cockney',4);
insert into questions(category_id, question, question_type, answer, difficulty) values (15,'The name of this language of the Philippines comes from the words meaning "of the river"','What is','tagalog',5);
insert into categories(category_id, category_name) values (16,'Teenage');
insert into questions(category_id, question, question_type, answer, difficulty) values (16,'This Jewish right of passage marks a boy''s 13th birthday','What is a','Bar Mitzvah',1);
insert into questions(category_id, question, question_type, answer, difficulty) values (16,'2-word alliterative term describing musical acts like ''N Sync & New Kids on the Block','What is a','boy band',2);
insert into questions(category_id, question, question_type, answer, difficulty) values (16,'Usually affecting teenage girls, it''s an extreme eating disorder marked by an excessive fear of being overweight','What is','anorexia',3);
insert into questions(category_id, question, question_type, answer, difficulty) values (16,'From the Latin for "adult", it''s the stage of physiological maturity that usually happens to teenagers','What is','puberty',4);
insert into questions(category_id, question, question_type, answer, difficulty) values (16,'A party known for being particularly "sweet" is typically thrown for North American girls when they turn this age.','What is','16',5);
insert into categories(category_id, category_name) values (17,'Get Your Sith Together');
insert into questions(category_id, question, question_type, answer, difficulty) values (17,'He''s 7 feet tall & the Millennium Falcon''s first mate, but he''s not much of a conversationalist','Who is','chewbacca',1);
insert into questions(category_id, question, question_type, answer, difficulty) values (17,'This syntactically challenged Jedi called Dagobah home','Who is','yoda',2);
insert into questions(category_id, question, question_type, answer, difficulty) values (17,'He was the bounty hunter in the Star Wars Original Trilogy seeking to capture Han Solo.','Who is','Boba Fett',3);
insert into questions(category_id, question, question_type, answer, difficulty) values (17,'He played Senator Bail Organa, Princess Leia''s adoptive father','Who is','Jimmy Smits',4);
insert into questions(category_id, question, question_type, answer, difficulty) values (17,'This character killed Qui Gon Jinn in Episode I','Who is','Darth Maul',5);
insert into categories(category_id, category_name) values (18,'I Like "Ike"');
insert into questions(category_id, question, question_type, answer, difficulty) values (18,'To solicit a free ride along a road','What is to','hitchhike',1);
insert into questions(category_id, question, question_type, answer, difficulty) values (18,'A sharp rise on a graph followed by a sharp decline','What is a','spike',2);
insert into questions(category_id, question, question_type, answer, difficulty) values (18,'Unbecoming conduct on the gridiron','What is','unsportmanlike',3);
insert into questions(category_id, question, question_type, answer, difficulty) values (18,'An embankment for controlling or holding back the waters of the sea or river.','What is a','dike',4);
insert into questions(category_id, question, question_type, answer, difficulty) values (18,'Knocking down all the pins on the first attempt for a round of bowling.','What is a','strike',5);
insert into categories(category_id, category_name) values (19,'History''s Mysteries');
insert into questions(category_id, question, question_type, answer, difficulty) values (19,'The Navy doesn''t like to attribute the loss of the USS Cyclops to forces in this spooky area','What is the','Bermuda Triangle',1);
insert into questions(category_id, question, question_type, answer, difficulty) values (19,'According to Plato, Solon, a great Greek lawgiver, went to Egypt & received the story of this lost land','What is','Atlantis',2);
insert into questions(category_id, question, question_type, answer, difficulty) values (19,'Also known as Rapa Nui, this Chilean island is known for strange statues & rongo-rongo hieroglyphs','What is','Easter Island',3);
insert into questions(category_id, question, question_type, answer, difficulty) values (19,'On a 50th anniversary, Lucia dos Santos accompanied Pope Paul VI to a shrine in this village in 1967','What is','Fatima',4);
insert into questions(category_id, question, question_type, answer, difficulty) values (19,'This Biblical prophet tells of an odd sight resembling "a wheel in the middle of a wheel"','Who is','Ezekiel',5);
insert into categories(category_id, category_name) values (20,'Packaging');
insert into questions(category_id, question, question_type, answer, difficulty) values (20,'In 1938 Clicquot Club Ginger Ale was the first soft drink sold in these','What are','cans',1);
insert into questions(category_id, question, question_type, answer, difficulty) values (20,'Whether AA jumbo ones of these remain AA jumbo may depend on the strength of their polystyrene cartons','What are','eggs',2);
insert into questions(category_id, question, question_type, answer, difficulty) values (20,'At the end of TV''s "Adventures of Rin Tin Tin", kids were told how to send in these from Shredded Wheat to get prizes','What are','box tops',3);
insert into questions(category_id, question, question_type, answer, difficulty) values (20,'Type of product whose package says, "Flatten as you go up"','What is','toothpaste',4);
insert into questions(category_id, question, question_type, answer, difficulty) values (20,'Very sensibly, in 2004 Tylenol introduced an EZ-Open Cap on medication for those who suffer from this','What is','arthritis',5);
insert into categories(category_id, category_name) values (21,'"S"-Ential Knowledge');
insert into questions(category_id, question, question_type, answer, difficulty) values (21,'Broadcast on the Dumont Network in 1946, "Faraway Hill" is considered the first TV show in this daytime genre','What is a','soap opera',1);
insert into questions(category_id, question, question_type, answer, difficulty) values (21,'Important newspapers published in this country include Diario de Cadiz & Diario de Mallorca','What is','Spain',2);
insert into questions(category_id, question, question_type, answer, difficulty) values (21,'The dog Laika, the first living creature in space, rode there aboard this Russian spacecraft','What is','sputnik',3);
insert into questions(category_id, question, question_type, answer, difficulty) values (21,'In the Bible that traitorous hussy Delilah had this man''s pride & joy shaved, & then turned him over to the enemy','Who is','samson',4);
insert into questions(category_id, question, question_type, answer, difficulty) values (21,'The daughter of the Titans Hyperion & Theia, she was the goddess of the Moon','Who is','selene',5);
insert into categories(category_id, category_name) values (22,'A CAT - egory');
insert into questions(category_id, question, question_type, answer, difficulty) values (22,'We envy the Egyptian mau cat, whose eyes are the gooseberry shade of this color','What is','green',1);
insert into questions(category_id, question, question_type, answer, difficulty) values (22,'The first Cornish Rex cat was the offspring of a tortie & a white barn cat in this part of SW England','What is','cornwall',2);
insert into questions(category_id, question, question_type, answer, difficulty) values (22,'Shulamith, a stray discovered in 1981, was the first American curl cat, named for its perky-looking pair of these','What are','ears',3);
insert into questions(category_id, question, question_type, answer, difficulty) values (22,'A relatively new breed of cat with very short legs bears the name of these little beings introduced in a 1900 book','What are','muchkins',4);
insert into questions(category_id, question, question_type, answer, difficulty) values (22,'The Balinese is basically a long-haired version of this other Asian cat','What is','siamese',5);
insert into categories(category_id, category_name) values (23,'Make My Car');
insert into questions(category_id, question, question_type, answer, difficulty) values (23,'The Sentra of your attention.','What is','nissan',1);
insert into questions(category_id, question, question_type, answer, difficulty) values (23,'The $120,000 S-class coupe; my friends all drive Porshes, I must make amends','What is','mercedes',2);
insert into questions(category_id, question, question_type, answer, difficulty) values (23,'The Rav4, which has the airbags8.','What is','toyota',3);
insert into questions(category_id, question, question_type, answer, difficulty) values (23,'The Sportage (Hint: SUV is 3 letters, too)','What is','kia',4);
insert into questions(category_id, question, question_type, answer, difficulty) values (23,'The A4 runs 4 rings around the competition.','What is','audi',5);
insert into categories(category_id, category_name) values (24,'Rymes With Rain');
insert into questions(category_id, question, question_type, answer, difficulty) values (24,'It''s a sheet of glass in a window','What is','pane',1);
insert into questions(category_id, question, question_type, answer, difficulty) values (24,'Pirates once plundered ships in an area of the Caribbean referred to as the Spanish this','What is','main',2);
insert into questions(category_id, question, question_type, answer, difficulty) values (24,'Of sound mind','What is','sane',3);
insert into questions(category_id, question, question_type, answer, difficulty) values (24,'Prop for Charlie Chaplin''s Little Tramp character','What is','cane',4);
insert into questions(category_id, question, question_type, answer, difficulty) values (24,'Sorghum or triticale','What is','grain',5);
